### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by bughoho** [Nukem9/IDASkins#1]
Could you provide a precompiled version?

**Comment by Nukem9** [comment]
Didn't even cross my mind. Here you go: https://github.com/Nukem9/IDASkins/releases/tag/1.4.0

**Comment by bughoho** [comment]
Thanks a lot!
But seems something is wrong.
If I jump from other tab to the CPU tab.this will be the case:
![20150830224519](https://cloud.githubusercontent.com/assets/10548054/9567780/96ad91da-4f69-11e5-911e-7b573ec6cc85.png)

**Comment by Nukem9** [comment]
I noticed this also, forgot about it for a while. I simply change the Qt stylesheet (no rendering functions) - so it's something to do with x64dbg itself and when the tabs are painted. Not really possible to fix it with this plugin only.

**Comment by bughoho** [comment]
Well.
It's a wonderful plugin,hope one day to solve this problem:)
